# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carparkpark.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


##page1


class Ui_CarParking(object):
    def setupUi(self, CarParking):
        CarParking.setObjectName("CarParking")
        CarParking.resize(600, 600)
        CarParking.setMinimumSize(QtCore.QSize(600, 600))
        CarParking.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/carpy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CarParking.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(CarParking)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -2, 601, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1") #pagename
        self.label_7 = QtWidgets.QLabel(self.page1)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Downloads/Express Yourself 70\'s Social Post (8).jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7") 
        self.NEXT1 = QtWidgets.QPushButton(self.page1) #clicknext
        self.NEXT1.setGeometry(QtCore.QRect(460, 40, 101, 51))
        self.NEXT1.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);") #font_next
        self.NEXT1.setObjectName("NEXT1") #clickname
        self.stackedWidget.addWidget(self.page1)


##page2


        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2") #pagename
        self.label_2 = QtWidgets.QLabel(self.page2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 621, 621))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/carbg2.1.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.Market = QtWidgets.QComboBox(self.page2) #clicknext
        self.Market.setGeometry(QtCore.QRect(180, 190, 261, 41))
        self.Market.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);") #font_next
        self.Market.setEditable(True)
        self.Market.setObjectName("Market")
        self.Market.addItem("")
        self.Market.addItem("")
        self.Market.addItem("")
        self.Market.addItem("")
        self.ParkingSlot = QtWidgets.QComboBox(self.page2)
        self.ParkingSlot.setGeometry(QtCore.QRect(260, 460, 81, 41))
        self.ParkingSlot.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);\n" #font_parkingslot
"")
        self.ParkingSlot.setObjectName("ParkingSlot")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingSlot.addItem("")
        self.ParkingDate = QtWidgets.QDateEdit(self.page2)
        self.ParkingDate.setGeometry(QtCore.QRect(200, 370, 191, 41))
        self.ParkingDate.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.ParkingDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 15), QtCore.QTime(0, 0, 0)))
        self.ParkingDate.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 15), QtCore.QTime(0, 0, 0)))
        self.ParkingDate.setObjectName("ParkingDate")
        self.NEXT2 = QtWidgets.QPushButton(self.page2)
        self.NEXT2.setGeometry(QtCore.QRect(490, 40, 91, 51))
        self.NEXT2.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);\n"
"")
        self.NEXT2.setObjectName("NEXT2")
        self.BACK2 = QtWidgets.QPushButton(self.page2)
        self.BACK2.setGeometry(QtCore.QRect(30, 50, 91, 51))
        self.BACK2.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);\n"
"")
        self.BACK2.setObjectName("BACK2")
        self.hour1 = QtWidgets.QCheckBox(self.page2)
        self.hour1.setGeometry(QtCore.QRect(30, 280, 121, 41))
        self.hour1.setStyleSheet("font: 75 8pt \"Arial\";\n"
"background-color: rgb(255, 170, 127);\n"
"")
        self.hour1.setObjectName("hour1")
        self.hour2 = QtWidgets.QCheckBox(self.page2)
        self.hour2.setGeometry(QtCore.QRect(170, 280, 121, 41))
        self.hour2.setStyleSheet("\n"
"font: 75 8pt \"Arial\";\n"
"background-color: rgb(255, 170, 127);\n"
"")
        self.hour2.setObjectName("hour2")
        self.hour3 = QtWidgets.QCheckBox(self.page2)
        self.hour3.setGeometry(QtCore.QRect(310, 280, 121, 41))
        self.hour3.setStyleSheet("font: 75 8pt \"Arial\";\n"
"\n"
"background-color: rgb(255, 170, 127);\n"
"\n"
"")
        self.hour3.setObjectName("hour3")
        self.hour4 = QtWidgets.QCheckBox(self.page2)
        self.hour4.setGeometry(QtCore.QRect(450, 280, 121, 41))
        self.hour4.setStyleSheet("\n"
"font: 75 8pt \"Arial\";\n"
"background-color: rgb(255, 170, 127);\n"
"\n"
"")
        self.hour4.setObjectName("hour4")
        self.stackedWidget.addWidget(self.page2)


##page3


        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3") #pagename
        self.label = QtWidgets.QLabel(self.page3)
        self.label.setGeometry(QtCore.QRect(0, 0, 611, 601))
        self.label.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 75 22pt \"Arial\";")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/carbg3.1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.NEXT3 = QtWidgets.QPushButton(self.page3)
        self.NEXT3.setGeometry(QtCore.QRect(480, 40, 91, 51))
        self.NEXT3.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);")
        self.NEXT3.setObjectName("NEXT3")
        self.Total = QtWidgets.QLabel(self.page3)
        self.Total.setGeometry(QtCore.QRect(270, 360, 71, 51))
        self.Total.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.Total.setObjectName("Total")
        self.BACK3 = QtWidgets.QPushButton(self.page3)
        self.BACK3.setGeometry(QtCore.QRect(30, 40, 91, 51))
        self.BACK3.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);\n"
"")
        self.BACK3.setObjectName("BACK3")
        self.Hour = QtWidgets.QLabel(self.page3)
        self.Hour.setGeometry(QtCore.QRect(280, 250, 51, 51))
        self.Hour.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);\n"
"")
        self.Hour.setObjectName("Hour")
        self.stackedWidget.addWidget(self.page3)


##page4


        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4") #pagename
        self.label_3 = QtWidgets.QLabel(self.page4)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/carbg4.7.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.NEXT4 = QtWidgets.QPushButton(self.page4)
        self.NEXT4.setGeometry(QtCore.QRect(470, 40, 91, 51))
        self.NEXT4.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);")
        self.NEXT4.setObjectName("NEXT4")
        self.MarketName = QtWidgets.QLabel(self.page4)
        self.MarketName.setGeometry(QtCore.QRect(320, 180, 221, 41))
        self.MarketName.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketName.setObjectName("MarketName")
        self.MarketHour = QtWidgets.QLabel(self.page4)
        self.MarketHour.setGeometry(QtCore.QRect(280, 330, 221, 41))
        self.MarketHour.setStyleSheet("font: 87 9pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketHour.setObjectName("MarketHour")
        self.MarketTotal = QtWidgets.QLabel(self.page4)
        self.MarketTotal.setGeometry(QtCore.QRect(290, 380, 61, 41))
        self.MarketTotal.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketTotal.setObjectName("MarketTotal")
        self.BACK4 = QtWidgets.QPushButton(self.page4)
        self.BACK4.setGeometry(QtCore.QRect(40, 40, 91, 51))
        self.BACK4.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);\n"
"")
        self.BACK4.setObjectName("BACK4")
        self.MarketSlot = QtWidgets.QLabel(self.page4)
        self.MarketSlot.setGeometry(QtCore.QRect(430, 280, 61, 41))
        self.MarketSlot.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketSlot.setObjectName("MarketSlot")
        self.MarketDate = QtWidgets.QLabel(self.page4)
        self.MarketDate.setGeometry(QtCore.QRect(270, 230, 191, 41))
        self.MarketDate.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketDate.setObjectName("MarketDate")
        self.stackedWidget.addWidget(self.page4)


##page5


        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.label_4 = QtWidgets.QLabel(self.page5)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 601, 621))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Downloads/carbg5.10.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.MarketNameBill = QtWidgets.QLabel(self.page5)
        self.MarketNameBill.setGeometry(QtCore.QRect(330, 190, 211, 41))
        self.MarketNameBill.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketNameBill.setText("")
        self.MarketNameBill.setObjectName("MarketNameBill")
        self.MarketHourBill = QtWidgets.QLabel(self.page5)
        self.MarketHourBill.setGeometry(QtCore.QRect(270, 340, 231, 41))
        self.MarketHourBill.setStyleSheet("font: 87 9pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketHourBill.setObjectName("MarketHourBill")
        self.MarketTotalBill = QtWidgets.QLabel(self.page5)
        self.MarketTotalBill.setGeometry(QtCore.QRect(300, 400, 61, 41))
        self.MarketTotalBill.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketTotalBill.setObjectName("MarketTotalBill")
        self.DONE = QtWidgets.QPushButton(self.page5)
        self.DONE.setGeometry(QtCore.QRect(480, 40, 91, 51))
        self.DONE.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 255, 127);")
        self.DONE.setObjectName("DONE")
        self.MarketSlotBill = QtWidgets.QLabel(self.page5)
        self.MarketSlotBill.setGeometry(QtCore.QRect(430, 290, 61, 41))
        self.MarketSlotBill.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketSlotBill.setObjectName("MarketSlotBill")
        self.MarketDateBill = QtWidgets.QLabel(self.page5)
        self.MarketDateBill.setGeometry(QtCore.QRect(270, 240, 201, 41))
        self.MarketDateBill.setStyleSheet("font: 87 14pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 170, 127);")
        self.MarketDateBill.setText("")
        self.MarketDateBill.setObjectName("MarketDateBill")
        self.stackedWidget.addWidget(self.page5)

        self.retranslateUi(CarParking)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CarParking)



##code



        #NEXT,BACK page(ComboBox)

        self.NEXT1.clicked.connect(self.go1)
        self.NEXT2.clicked.connect(self.go2)
        self.NEXT3.clicked.connect(self.go3)
        self.NEXT4.clicked.connect(self.go4)
        self.DONE.clicked.connect(self.go5)
        self.BACK2.clicked.connect(self.go6)
        self.BACK3.clicked.connect(self.go7)
        self.BACK4.clicked.connect(self.go8)

        #SelectMarket(ComboBox)

        self.Market.activated.connect(self.market)

        #SelectTime(CheckBox)

        self.hour1.clicked.connect(self.time)
        self.hour2.clicked.connect(self.time)
        self.hour3.clicked.connect(self.time)
        self.hour4.clicked.connect(self.time)

        #SelectDate(DateEdit)

        self.ParkingDate.dateChanged.connect(self.date)

        #SelectSlot(ComboBox)

        self.ParkingSlot.activated.connect(self.slot)
        

        
    ##NEXT,BACK page

    def go1(self):
        self.stackedWidget.setCurrentIndex(1)
    def go2(self):
        self.stackedWidget.setCurrentIndex(2)
    def go3(self):
        self.stackedWidget.setCurrentIndex(3)
    def go4(self):
        self.stackedWidget.setCurrentIndex(4)
    def go5(self):
        self.stackedWidget.setCurrentIndex(0)
    def go6(self):
        self.stackedWidget.setCurrentIndex(0)
    def go7(self):
        self.stackedWidget.setCurrentIndex(1)
    def go8(self):
        self.stackedWidget.setCurrentIndex(2)

    ##SelectMarket

    def market(self):
        
        self.marketzone = self.Market.currentText()

        #result_zone
        self.MarketName.setText(" "+self.marketzone)
        self.MarketNameBill.setText(" "+self.marketzone)

    ##SelectTime

    #howmanyhours(page3)

    def time(self):
        time_hour = 0

        if self.hour1.isChecked():
            time_hour +=1
        if self.hour2.isChecked():
            time_hour +=1
        if self.hour3.isChecked():
            time_hour +=1
        if self.hour4.isChecked():
            time_hour +=1
        
        total = time_hour*20 #calculatetotal

    #parkingtime(page4,5)

        if self.hour1.isChecked():
            z1 = "05.00-06.00,"
        else:
            z1 = ""

        if self.hour2.isChecked():
            z2 = "06.00-07.00,"
        else:
            z2 = ""

        if self.hour3.isChecked():
            z3 = "07.00-08.00,"
        else:
            z3 = ""

        if self.hour4.isChecked():
            z4 = "08.00-09.00"
        else:
            z4 = ""

        #result_hour_page3
        self.Hour.setText("  "+str(time_hour))
        #result_total_page3
        self.Total.setText("  "+str(total))

        #result_time_page4
        self.MarketHour.setText(str(z1)+str(z2)+"\n"+str(z3)+str(z4))
        #result_total_page4
        self.MarketTotal.setText("  "+str(total))

        #result_time_page5
        self.MarketHourBill.setText(str(z1)+str(z2)+"\n"+str(z3)+str(z4))
        #result_total_page5
        self.MarketTotalBill.setText("  "+str(total))

    ##SelectDate
    
    def date(self, qDate):
        parkdate = ('{0}/{1}/{2}'.format(qDate.month(), qDate.day(), qDate.year()))

        #result_date_page4
        self.MarketDate.setText("  "+parkdate)
        #result_date_page5
        self.MarketDateBill.setText("  "+parkdate)

    ##SelectSlot
    
    def slot(self):
        self.parkslot = self.ParkingSlot.currentText()

        #result_slot_page4
        self.MarketSlot.setText("  "+self.parkslot)
        #result_slot_page5
        self.MarketSlotBill.setText("  "+self.parkslot)



    def retranslateUi(self, CarParking):
        _translate = QtCore.QCoreApplication.translate
        CarParking.setWindowTitle(_translate("CarParking", "CarParking"))
        self.NEXT1.setText(_translate("CarParking", "NEXT"))
        self.Market.setItemText(0, _translate("CarParking", "----"))
        self.Market.setItemText(1, _translate("CarParking", "FlowerMarket"))
        self.Market.setItemText(2, _translate("CarParking", "PorkMarket"))
        self.Market.setItemText(3, _translate("CarParking", "VeganMarket"))
        self.ParkingSlot.setItemText(0, _translate("CarParking", "----"))
        self.ParkingSlot.setItemText(1, _translate("CarParking", "1A"))
        self.ParkingSlot.setItemText(2, _translate("CarParking", "1B"))
        self.ParkingSlot.setItemText(3, _translate("CarParking", "1C"))
        self.ParkingSlot.setItemText(4, _translate("CarParking", "2A"))
        self.ParkingSlot.setItemText(5, _translate("CarParking", "2B"))
        self.ParkingSlot.setItemText(6, _translate("CarParking", "2C"))
        self.NEXT2.setText(_translate("CarParking", "NEXT"))
        self.BACK2.setText(_translate("CarParking", "BACK"))
        self.hour1.setText(_translate("CarParking", "05.00-06.00"))
        self.hour2.setText(_translate("CarParking", "06.00-07.00"))
        self.hour3.setText(_translate("CarParking", "07.00-08.00"))
        self.hour4.setText(_translate("CarParking", "08.00-09.00"))
        self.NEXT3.setText(_translate("CarParking", "NEXT"))
        self.Total.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.BACK3.setText(_translate("CarParking", "BACK"))
        self.Hour.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.NEXT4.setText(_translate("CarParking", "NEXT"))
        self.MarketName.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketHour.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketTotal.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.BACK4.setText(_translate("CarParking", "BACK"))
        self.MarketSlot.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketDate.setWhatsThis(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketDate.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketHourBill.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MarketTotalBill.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.DONE.setText(_translate("CarParking", "DONE"))
        self.MarketSlotBill.setText(_translate("CarParking", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))



if __name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CarParking = QtWidgets.QWidget()
    ui = Ui_CarParking()
    ui.setupUi(CarParking)
    CarParking.show()
    #sys.exit(app.exac_())
